# Файл docker-compose начинается с тега версии

version: "3"

# Раздел описания сервисов (1 сервис = 1 контейнер)
services:

  # Описываем сервисы клтиент-серверного приложения.

  server:
 
    # Команда "build" задает путь к файлу Dockerfile для создания образа
    build: server/

    # Команда, которую нужно запустить после создания образа
    command: python ./server.py

    # Для обращения к серверу с нашего компьютера находясь за пределами контейнера,
    # необходимо организовать перенаправление порта сервера на порт компьютера.
    # Команда 'ports' организует связь порта локального компьютера с портом контейнера
    ports:
      - 1234:1234

  client:

    build: client/

    command: python ./client.py

    # Описания типа сети связывающей контейнеры и локальный host-компьютер
    network_mode: host

    # Команда 'depends_on' позволяет указывать, должен ли сервис,
    # прежде чем запуститься, ждать, когда будут готовы к работе другие сервисы.
    # Нам нужно, чтобы сервис 'client' дождался бы готовности к работе сервиса 'server'.
    depends_on:
      - server